Fix Floating Text Particle
Creeperface01/Nukkit pull request #14
Opened 2017-09-22 20:36 UTC by Goodstuff4UonYT

2017-09-22 20:53 UTC, ghost requested changes

2017-09-22 20:53 UTC, NycuRO commented on src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java
> +                    .putFloat(Entity.DATA_TYPE_FLOAT, 0.01f) //zero causes problems on debug builds?
use NULL , not 0

2017-09-22 21:13 UTC, Goodstuff4UonYT commented on src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java
> +                    .putFloat(Entity.DATA_TYPE_FLOAT, 0.01f) //zero causes problems on debug builds?
@Creeperface01 What do you think?

2017-09-23 05:42 UTC, Creeperface01 commented on src/main/java/cn/nukkit/level/particle/FloatingTextParticle.java
> +                    .putFloat(Entity.DATA_TYPE_FLOAT, 0.01f) //zero causes problems on debug builds?
Idk, you can test null

2017-09-23 05:43 UTC, merged